language: R
warnings_are_errors: true
sudo: required
cache: packages

matrix:
    include:
        - r: release
        - r: devel
        - r: oldrel
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true
        - os: osx
          r: devel
          before_install: ''
          disable_homebrew: true
    allow_failures:
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true
        - os: osx
          r: devel
          before_install: ''
          disable_homebrew: true

before_install:
    - cd rpkg
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev


notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
      - covr
